import { PrismaClient, EmploymentType, ExperienceLevel, EducationLevel, SalaryDisclosure, OpportunityType, FundingDisclosure, OrganizationIndustry, OrganizationType } from '@prisma/client';
import { C, slugify } from './seed-data';

const prisma = new PrismaClient();

const ORGS: [string,string,string,string,string,boolean,string][] = [
  ["Safaricom PLC","safaricom","TELECOMMUNICATIONS","PUBLIC_LISTED_COMPANY","Nairobi",true,"Safaricom is Kenya's leading telecommunications company, providing mobile voice, data, financial services (M-Pesa), and enterprise solutions to millions of Kenyans across the country and beyond."],
  ["Equity Group Holdings","equity-bank","BANKING","PUBLIC_LISTED_COMPANY","Nairobi",true,"Equity Bank is one of Kenya's largest banking groups, offering financial services to individuals, SMEs, and large corporations across East Africa."],
  ["Kenya Revenue Authority","kra","GOVERNMENT_PUBLIC_ADMIN","STATE_CORPORATION","Nairobi",true,"KRA is the principal tax collection agency of the Government of Kenya, responsible for assessment, collection, and accounting of all revenues."],
  ["UNEP Nairobi","unep-nairobi","INTERNATIONAL_DEVELOPMENT","NGO_INTERNATIONAL","Nairobi",true,"UNEP is the leading global environmental authority that sets the global environmental agenda."],
  ["Cooperative Bank of Kenya","co-op-bank","BANKING","PUBLIC_LISTED_COMPANY","Nairobi",true,"Cooperative Bank is a leading commercial bank in Kenya serving individuals, businesses, and cooperative societies."],
  ["KCB Group","kcb-group","BANKING","PUBLIC_LISTED_COMPANY","Nairobi",true,"KCB Group is the largest financial services group in East Africa."],
  ["County Gov. Mombasa","county-gov-mombasa","GOVERNMENT_PUBLIC_ADMIN","COUNTY_GOVERNMENT","Mombasa",true,"The County Government of Mombasa is responsible for local governance and development in Mombasa County."],
  ["UNICEF Kenya","unicef-kenya","INTERNATIONAL_DEVELOPMENT","NGO_INTERNATIONAL","Nairobi",true,"UNICEF Kenya works to protect the rights of every child in Kenya."],
  ["Naivas Supermarket","naivas","RETAIL","PRIVATE_COMPANY","Nairobi",true,"Naivas is one of Kenya's fastest-growing supermarket chains."],
  ["KenGen","kengen","ENERGY","STATE_CORPORATION","Nairobi",true,"KenGen produces about 75% of electricity consumed in Kenya."],
  ["NCBA Bank","ncba-bank","BANKING","PUBLIC_LISTED_COMPANY","Nairobi",true,"NCBA Bank offers retail, corporate, and investment banking."],
  ["Bidco Africa","bidco-africa","MANUFACTURING","PRIVATE_COMPANY","Nairobi",true,"Bidco Africa is a leading consumer goods manufacturer in East Africa."],
  ["East African Breweries","eabl","MANUFACTURING","PUBLIC_LISTED_COMPANY","Nairobi",true,"EABL is a leading beverage manufacturer in East Africa."],
  ["Amref Health Africa","amref-health","NON_PROFIT","NGO_LOCAL","Nairobi",true,"Amref is Africa's largest health NGO."],
  ["Telkom Kenya","telkom-kenya","TELECOMMUNICATIONS","PRIVATE_COMPANY","Nairobi",false,"Telkom Kenya offers fixed-line, mobile, and enterprise data services."],
  ["World Vision Kenya","world-vision-kenya","NON_PROFIT","NGO_INTERNATIONAL","Nairobi",true,"World Vision Kenya improves the lives of children and communities."],
  ["University of Nairobi","university-of-nairobi","EDUCATION","UNIVERSITY","Nairobi",true,"UoN is the oldest and largest university in Kenya."],
  ["Kenya Airways","kenya-airways","AVIATION","PUBLIC_LISTED_COMPANY","Nairobi",true,"Kenya Airways is the flag carrier airline of Kenya."],
  ["Ministry of Education","ministry-education","GOVERNMENT_PUBLIC_ADMIN","NATIONAL_GOVERNMENT","Nairobi",true,"The Ministry of Education is responsible for education policy in Kenya."],
  ["Techno Brain","techno-brain","INFORMATION_TECHNOLOGY","PRIVATE_COMPANY","Nairobi",false,"Techno Brain is a leading IT solutions provider in Africa."],
];

type JI = { t: string; o: string; c: string; s: string; ct: string; ci: string; et: EmploymentType; el: ExperienceLevel; ed: EducationLevel; smin: number|null; smax: number|null; sd: SalaryDisclosure; f: boolean; d: string; };

const JOBS: JI[] = [
  {t:"Senior Software Engineer",o:"safaricom",c:"TECHNOLOGY",s:"SOFTWARE_ENGINEERING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"BACHELORS",smin:200000,smax:350000,sd:"SHOW_RANGE",f:true,d:"Safaricom is seeking an experienced Senior Software Engineer to join our Digital Engineering team. You will design, develop, and maintain scalable enterprise applications serving millions of M-Pesa users across Kenya. The ideal candidate has strong experience in Java, Spring Boot, and microservices architecture. You will collaborate with cross-functional teams including product managers, designers, and QA engineers to deliver high-quality software solutions. This role offers competitive compensation, career growth opportunities, and the chance to make a real impact on financial inclusion in Kenya."},
  {t:"Data Analyst",o:"kra",c:"TECHNOLOGY",s:"DATA_SCIENCE",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:120000,smax:180000,sd:"SHOW_RANGE",f:true,d:"Kenya Revenue Authority is looking for a skilled Data Analyst to join our Business Intelligence team. You will analyze large datasets to identify tax compliance patterns, revenue leakages, and trends. Proficiency in SQL, Python, and data visualization tools like Tableau or Power BI is required. The role involves creating dashboards, generating reports for senior management, and supporting data-driven decision making across the authority."},
  {t:"IT Support Intern",o:"equity-bank",c:"TECHNOLOGY",s:"IT_SUPPORT",ct:"Kisumu",ci:"Kisumu",et:"INTERNSHIP",el:"ENTRY",ed:"DIPLOMA",smin:15000,smax:25000,sd:"SHOW_RANGE",f:false,d:"Equity Bank is offering a 6-month IT Support Internship at our Kisumu branch. You will gain hands-on experience in troubleshooting hardware and software issues, managing network infrastructure, and providing technical support to bank staff. This is an excellent opportunity for fresh graduates looking to start a career in IT within the banking sector."},
  {t:"Project Coordinator",o:"unicef-kenya",c:"OPERATIONS_ADMIN",s:"PROJECT_COORDINATION",ct:"Nairobi",ci:"Nairobi",et:"CONTRACT",el:"MID",ed:"BACHELORS",smin:150000,smax:220000,sd:"SHOW_RANGE",f:true,d:"UNICEF Kenya seeks a Project Coordinator to manage education program implementation across 5 counties. You will coordinate with government officials, NGO partners, and community leaders to ensure timely delivery of program activities. Strong project management skills and experience in the development sector are essential for this role."},
  {t:"Public Health Officer",o:"county-gov-mombasa",c:"HEALTHCARE",s:"PUBLIC_HEALTH",ct:"Mombasa",ci:"Mombasa",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:80000,smax:120000,sd:"SHOW_RANGE",f:true,d:"The County Government of Mombasa is recruiting a Public Health Officer to lead community health initiatives. You will be responsible for disease surveillance, health education campaigns, and coordination of public health emergency responses. A degree in Public Health or Environmental Health is required, along with registration with the relevant professional body."},
  {t:"Financial Analyst",o:"kcb-group",c:"FINANCE_ACCOUNTING",s:"FINANCIAL_ANALYSIS",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:130000,smax:200000,sd:"SHOW_RANGE",f:false,d:"KCB Group is hiring a Financial Analyst to support strategic planning and investment decisions. You will perform financial modeling, conduct variance analysis, and prepare management reports. CFA or CPA qualification is an added advantage. Strong analytical skills and proficiency in Excel and financial planning tools are essential."},
  {t:"Marketing Manager",o:"eabl",c:"MARKETING_COMMUNICATIONS",s:"BRAND_MANAGEMENT",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"MASTERS",smin:250000,smax:400000,sd:"SHOW_RANGE",f:true,d:"East African Breweries Limited seeks a dynamic Marketing Manager to lead brand strategy for our premium product portfolio. You will develop and execute marketing campaigns, manage agency relationships, analyze market trends, and drive brand growth across Kenya. At least 7 years of marketing experience in FMCG is required."},
  {t:"Registered Nurse",o:"amref-health",c:"HEALTHCARE",s:"NURSING",ct:"Nakuru",ci:"Nakuru",et:"FULL_TIME",el:"MID",ed:"DIPLOMA",smin:60000,smax:90000,sd:"SHOW_RANGE",f:false,d:"Amref Health Africa is looking for a Registered Nurse to join our mobile health clinics in Nakuru. You will provide primary healthcare services, conduct community health education, and support maternal and child health programs. Registration with the Nursing Council of Kenya is mandatory."},
  {t:"Civil Engineer",o:"county-gov-mombasa",c:"ENGINEERING",s:"CIVIL_ENGINEERING",ct:"Mombasa",ci:"Mombasa",et:"CONTRACT",el:"MID",ed:"BACHELORS",smin:100000,smax:180000,sd:"SHOW_RANGE",f:false,d:"The County Government of Mombasa requires a Civil Engineer to oversee infrastructure development projects including road construction, drainage systems, and public buildings. You will manage contractors, ensure compliance with engineering standards, and prepare project progress reports."},
  {t:"HR Business Partner",o:"safaricom",c:"HUMAN_RESOURCES",s:"HR_GENERALIST",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"BACHELORS",smin:180000,smax:280000,sd:"SHOW_RANGE",f:false,d:"Safaricom is looking for an HR Business Partner to support our Technology division. You will partner with business leaders to drive people strategy, manage talent development programs, and ensure effective employee relations. IHRM certification and at least 6 years of HR experience in a fast-paced environment are required."},
  {t:"Accountant",o:"co-op-bank",c:"FINANCE_ACCOUNTING",s:"ACCOUNTING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:80000,smax:130000,sd:"SHOW_RANGE",f:false,d:"Cooperative Bank of Kenya is seeking a qualified Accountant to join our finance team. You will prepare financial statements, manage accounts payable and receivable, reconcile bank statements, and support the annual audit process. CPA Kenya qualification is required with at least 3 years of accounting experience."},
  {t:"Business Development Executive",o:"techno-brain",c:"SALES_BUSINESS",s:"BUSINESS_DEVELOPMENT",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:100000,smax:160000,sd:"SHOW_RANGE",f:false,d:"Techno Brain is hiring a Business Development Executive to drive growth in our IT solutions division. You will identify new business opportunities, build relationships with prospective clients, prepare proposals, and negotiate contracts. Experience selling IT services to enterprise clients in East Africa is preferred."},
  {t:"Procurement Officer",o:"kengen",c:"SUPPLY_CHAIN",s:"PROCUREMENT",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:90000,smax:140000,sd:"SHOW_RANGE",f:false,d:"KenGen is recruiting a Procurement Officer to manage the procurement of goods and services for our geothermal operations. You will handle tender processes, evaluate supplier bids, and ensure compliance with public procurement regulations. CIPS qualification and experience in the energy sector are added advantages."},
  {t:"Lecturer - Computer Science",o:"university-of-nairobi",c:"EDUCATION",s:"LECTURING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"DOCTORATE",smin:150000,smax:250000,sd:"SHOW_RANGE",f:false,d:"The University of Nairobi, Department of Computer Science, invites applications for a Lecturer position. You will teach undergraduate and postgraduate courses, supervise research, and contribute to the department's academic programs. A PhD in Computer Science or a related field and demonstrated research capability are required."},
  {t:"Graphic Designer",o:"bidco-africa",c:"CREATIVE_DESIGN",s:"GRAPHIC_DESIGN",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"DIPLOMA",smin:50000,smax:80000,sd:"SHOW_RANGE",f:false,d:"Bidco Africa is looking for a creative Graphic Designer to join our Brand & Communications team. You will create visual content for digital and print media, design packaging materials, and support marketing campaigns. Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign) is required."},
  {t:"Network Administrator",o:"telkom-kenya",c:"TECHNOLOGY",s:"NETWORK_ADMIN",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"DIPLOMA",smin:80000,smax:130000,sd:"SHOW_RANGE",f:false,d:"Telkom Kenya is hiring a Network Administrator to manage our enterprise network infrastructure. You will monitor network performance, troubleshoot connectivity issues, configure routers and switches, and ensure network security. CCNA or equivalent certification is required."},
  {t:"Legal Officer",o:"ncba-bank",c:"LEGAL",s:"CORPORATE_LAW",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:120000,smax:200000,sd:"SHOW_RANGE",f:false,d:"NCBA Bank is seeking a Legal Officer to provide legal advice on banking operations, regulatory compliance, and contract management. You will review and draft legal documents, manage litigation matters, and ensure the bank complies with all applicable laws and regulations. Admission to the Kenyan Bar is required."},
  {t:"Chef de Partie",o:"naivas",c:"HOSPITALITY",s:"CHEF_COOKING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"CERTIFICATE",smin:35000,smax:55000,sd:"SHOW_RANGE",f:false,d:"Naivas Supermarket is expanding our in-store bakery and food service operations and is looking for a Chef de Partie. You will be responsible for food preparation, maintaining kitchen hygiene standards, and managing a small team. Experience in a commercial kitchen environment is essential."},
  {t:"Social Worker",o:"world-vision-kenya",c:"NONPROFIT",s:"SOCIAL_WORK",ct:"Kakamega",ci:"Kakamega",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:60000,smax:90000,sd:"SHOW_RANGE",f:false,d:"World Vision Kenya is recruiting a Social Worker to implement child protection programs in Kakamega County. You will conduct community assessments, provide psychosocial support, and work with local authorities to strengthen child protection systems. A degree in Social Work or related field is required."},
  {t:"Mechanical Engineer",o:"kengen",c:"ENGINEERING",s:"MECHANICAL_ENGINEERING",ct:"Nakuru",ci:"Nakuru",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:100000,smax:170000,sd:"SHOW_RANGE",f:false,d:"KenGen has an opening for a Mechanical Engineer to join our geothermal power plant maintenance team. You will conduct preventive and corrective maintenance on turbines, pumps, and other mechanical equipment. Registration with EBK is required."},
  {t:"Digital Marketing Specialist",o:"safaricom",c:"MARKETING_COMMUNICATIONS",s:"DIGITAL_MARKETING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:100000,smax:160000,sd:"SHOW_RANGE",f:false,d:"Safaricom is looking for a Digital Marketing Specialist to drive online customer acquisition and engagement. You will manage digital campaigns across social media, search engines, and email platforms, analyze performance metrics, and optimize campaigns for better ROI. Google Ads and Meta Blueprint certifications are preferred."},
  {t:"First Officer Pilot",o:"kenya-airways",c:"AVIATION",s:"COMMERCIAL_PILOT",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"JUNIOR",ed:"BACHELORS",smin:250000,smax:400000,sd:"SHOW_RANGE",f:true,d:"Kenya Airways is recruiting First Officers for our domestic and regional fleet. You will assist the Captain in operating flights safely and efficiently. A valid Commercial Pilot License (CPL) with instrument rating and at least 250 hours total flight time are required. Type rating on our fleet aircraft will be provided."},
  {t:"Agricultural Extension Officer",o:"ministry-education",c:"AGRICULTURE",s:"AGRICULTURAL_EXTENSION",ct:"Eldoret",ci:"Eldoret",et:"FULL_TIME",el:"ENTRY",ed:"DIPLOMA",smin:40000,smax:60000,sd:"SHOW_RANGE",f:false,d:"The Ministry of Agriculture is recruiting Agricultural Extension Officers to support farmers in Uasin Gishu County. You will provide training on modern farming techniques, facilitate access to agricultural inputs, and promote value addition in crop and livestock production across the county."},
  {t:"UX/UI Designer",o:"safaricom",c:"CREATIVE_DESIGN",s:"UX_UI_DESIGN",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:120000,smax:200000,sd:"SHOW_RANGE",f:false,d:"Safaricom is hiring a UX/UI Designer to create intuitive and engaging digital experiences for our mobile apps and web platforms. You will conduct user research, create wireframes and prototypes, and collaborate with developers to implement designs. A strong portfolio demonstrating user-centered design is required."},
  {t:"Mathematics Teacher",o:"ministry-education",c:"EDUCATION",s:"SECONDARY_EDUCATION",ct:"Kiambu",ci:"Kiambu",et:"FULL_TIME",el:"ENTRY",ed:"BACHELORS",smin:35000,smax:50000,sd:"SHOW_RANGE",f:false,d:"The Teachers Service Commission is recruiting Mathematics teachers for secondary schools in Kiambu County. You will teach mathematics to form 1-4 students, prepare lesson plans, assess student progress, and participate in co-curricular activities. A Bachelor of Education (Science) with mathematics as a teaching subject is required."},
  {t:"Cybersecurity Analyst",o:"safaricom",c:"TECHNOLOGY",s:"CYBER_SECURITY",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:150000,smax:250000,sd:"SHOW_RANGE",f:false,d:"Safaricom is seeking a Cybersecurity Analyst to protect our digital infrastructure and customer data. You will monitor security events, conduct vulnerability assessments, respond to incidents, and implement security controls. CISSP, CEH, or equivalent certification is preferred. Experience with SIEM tools and penetration testing is essential."},
  {t:"Quantity Surveyor",o:"county-gov-mombasa",c:"ARCHITECTURE_CONSTRUCTION",s:"QUANTITY_SURVEYING",ct:"Mombasa",ci:"Mombasa",et:"CONTRACT",el:"MID",ed:"BACHELORS",smin:90000,smax:150000,sd:"SHOW_RANGE",f:false,d:"The County Government of Mombasa requires a Quantity Surveyor for ongoing infrastructure projects. You will prepare bill of quantities, conduct cost estimates, evaluate contractor claims, and ensure value for money in project delivery. Registration with the Board of Registration of Quantity Surveyors is required."},
  {t:"Customer Service Rep",o:"equity-bank",c:"CUSTOMER_SERVICE",s:"CUSTOMER_SUPPORT",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"ENTRY",ed:"DIPLOMA",smin:30000,smax:45000,sd:"SHOW_RANGE",f:false,d:"Equity Bank is hiring Customer Service Representatives for our contact center. You will handle customer inquiries via phone, email, and chat, resolve complaints, and provide information about our products and services. Excellent communication skills and a passion for customer service are essential."},
  {t:"DevOps Engineer",o:"safaricom",c:"TECHNOLOGY",s:"DEVOPS_CLOUD",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"BACHELORS",smin:200000,smax:350000,sd:"SHOW_RANGE",f:true,d:"Safaricom is looking for a DevOps Engineer to automate our CI/CD pipelines and manage cloud infrastructure on AWS and Azure. You will implement infrastructure as code using Terraform, manage Kubernetes clusters, and ensure system reliability and scalability. Experience with Docker, Kubernetes, and cloud platforms is essential."},
  {t:"M&E Officer",o:"unicef-kenya",c:"INTERNATIONAL_DEVELOPMENT",s:"MONITORING_EVALUATION",ct:"Nairobi",ci:"Nairobi",et:"CONTRACT",el:"MID",ed:"MASTERS",smin:140000,smax:200000,sd:"SHOW_RANGE",f:false,d:"UNICEF Kenya is seeking an M&E Officer to design and implement monitoring and evaluation frameworks for our education programs. You will collect and analyze data, prepare reports for donors, and provide recommendations for program improvement. Experience in M&E within the development sector is required."},
  {t:"Sales Representative",o:"naivas",c:"RETAIL",s:"RETAIL_SALES",ct:"Nakuru",ci:"Nakuru",et:"FULL_TIME",el:"ENTRY",ed:"HIGH_SCHOOL",smin:25000,smax:35000,sd:"SHOW_RANGE",f:false,d:"Naivas Supermarket is hiring Sales Representatives for our Nakuru branch. You will assist customers, manage product displays, process transactions, and maintain store cleanliness. Previous retail experience is preferred but not required as training will be provided."},
  {t:"Environmental Officer",o:"county-gov-mombasa",c:"ENVIRONMENTAL_SUSTAINABILITY",s:"ENVIRONMENTAL_MANAGEMENT",ct:"Mombasa",ci:"Mombasa",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:70000,smax:110000,sd:"SHOW_RANGE",f:false,d:"The County Government of Mombasa is recruiting an Environmental Officer to oversee environmental compliance and conservation programs. You will conduct environmental impact assessments, enforce environmental regulations, and coordinate waste management initiatives across the county."},
  {t:"Electrical Engineer",o:"kengen",c:"ENGINEERING",s:"ELECTRICAL_ENGINEERING",ct:"Nakuru",ci:"Nakuru",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:100000,smax:180000,sd:"SHOW_RANGE",f:false,d:"KenGen is hiring Electrical Engineers to support our power generation operations. You will maintain electrical equipment, design power distribution systems, and ensure compliance with electrical safety standards. Registration with the Engineers Board of Kenya is required."},
  {t:"Content Writer",o:"safaricom",c:"MEDIA_PUBLISHING",s:"CONTENT_CREATION",ct:"Nairobi",ci:"Nairobi",et:"FREELANCE",el:"MID",ed:"BACHELORS",smin:40000,smax:80000,sd:"NEGOTIABLE",f:false,d:"Safaricom is looking for freelance Content Writers to create engaging blog posts, social media content, and marketing copy. You will research topics, write SEO-optimized content, and adapt tone for different platforms. Strong writing skills and the ability to meet tight deadlines are essential."},
  {t:"Data Entry Clerk",o:"kra",c:"OPERATIONS_ADMIN",s:"DATA_ENTRY",ct:"Nairobi",ci:"Nairobi",et:"TEMPORARY",el:"ENTRY",ed:"HIGH_SCHOOL",smin:20000,smax:30000,sd:"SHOW_RANGE",f:false,d:"Kenya Revenue Authority requires temporary Data Entry Clerks to support our tax registration drive. You will accurately enter taxpayer information into our database, verify data accuracy, and maintain organized records. Proficiency in Microsoft Office and a typing speed of at least 40 WPM are required."},
  {t:"Architect",o:"county-gov-mombasa",c:"ARCHITECTURE_CONSTRUCTION",s:"ARCHITECTURE",ct:"Mombasa",ci:"Mombasa",et:"CONTRACT",el:"SENIOR",ed:"MASTERS",smin:150000,smax:250000,sd:"SHOW_RANGE",f:false,d:"The County Government of Mombasa seeks a registered Architect to lead the design of affordable housing projects. You will prepare architectural drawings, coordinate with engineers, and ensure designs comply with building codes. Registration with the Architectural Association of Kenya is required."},
  {t:"Insurance Underwriter",o:"ncba-bank",c:"INSURANCE",s:"UNDERWRITING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:90000,smax:150000,sd:"SHOW_RANGE",f:false,d:"NCBA Insurance is looking for an Underwriter to assess risk and determine coverage terms for our corporate clients. You will analyze applications, review financial statements, and make underwriting decisions. A degree in Insurance, Finance, or related field and professional insurance certification are required."},
  {t:"Clinical Psychologist",o:"ministry-education",c:"PSYCHOLOGY_COUNSELING",s:"CLINICAL_PSYCHOLOGY",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"MASTERS",smin:130000,smax:200000,sd:"SHOW_RANGE",f:false,d:"The Ministry of Health is seeking a Clinical Psychologist for a national mental health program. You will provide psychological assessments, therapy, and counseling services, and train healthcare workers in basic mental health support. Registration with the Kenya Psychological Association is required."},
  {t:"Manufacturing Supervisor",o:"bidco-africa",c:"MANUFACTURING",s:"PRODUCTION_MANAGEMENT",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"DIPLOMA",smin:60000,smax:90000,sd:"SHOW_RANGE",f:false,d:"Bidco Africa is hiring a Manufacturing Supervisor for our edible oils production line. You will oversee daily production operations, ensure quality standards, manage shift schedules, and drive continuous improvement initiatives. Experience in food manufacturing is preferred."},
  {t:"Plumber",o:"county-gov-mombasa",c:"SKILLED_TRADES",s:"PLUMBING",ct:"Mombasa",ci:"Mombasa",et:"CONTRACT",el:"MID",ed:"CERTIFICATE",smin:30000,smax:50000,sd:"SHOW_RANGE",f:false,d:"The County Government of Mombasa requires qualified Plumbers for public housing maintenance. You will install and repair plumbing systems, read blueprints, and ensure compliance with plumbing codes. A valid plumbing certificate and at least 3 years of experience are required."},
  {t:"Research Scientist",o:"unep-nairobi",c:"SCIENCE_RESEARCH",s:"ENVIRONMENTAL_SCIENCE",ct:"Nairobi",ci:"Nairobi",et:"CONTRACT",el:"SENIOR",ed:"DOCTORATE",smin:200000,smax:350000,sd:"SHOW_RANGE",f:true,d:"UNEP is seeking a Research Scientist to lead environmental research projects focusing on climate change adaptation in East Africa. You will design research methodologies, collect and analyze environmental data, publish research papers, and present findings at international conferences. A PhD in Environmental Science or related field is required."},
  {t:"Management Consultant",o:"techno-brain",c:"CONSULTING",s:"MANAGEMENT_CONSULTING",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"SENIOR",ed:"MASTERS",smin:200000,smax:350000,sd:"SHOW_RANGE",f:false,d:"Techno Brain is seeking a Management Consultant to advise clients on digital transformation strategies. You will conduct business analysis, develop recommendations, and support implementation of technology solutions. An MBA and at least 8 years of consulting experience are preferred."},
  {t:"Video Editor",o:"safaricom",c:"CREATIVE_DESIGN",s:"VIDEO_EDITING",ct:"Nairobi",ci:"Nairobi",et:"FREELANCE",el:"MID",ed:"DIPLOMA",smin:30000,smax:60000,sd:"NEGOTIABLE",f:false,d:"Safaricom is looking for a freelance Video Editor to create promotional videos, social media content, and corporate documentaries. Proficiency in Adobe Premiere Pro, After Effects, and DaVinci Resolve is required. A strong portfolio showcasing your video editing skills is essential."},
  {t:"Pharmacist",o:"equity-bank",c:"HEALTHCARE",s:"PHARMACY",ct:"Kisumu",ci:"Kisumu",et:"FULL_TIME",el:"MID",ed:"BACHELORS",smin:80000,smax:130000,sd:"SHOW_RANGE",f:false,d:"A leading pharmacy chain in Kisumu is looking for a licensed Pharmacist. You will dispense medications, provide drug information to patients, manage inventory, and ensure compliance with pharmacy regulations. Registration with the Pharmacy and Poisons Board of Kenya is mandatory."},
  {t:"Electrician",o:"kengen",c:"SKILLED_TRADES",s:"ELECTRICIAN",ct:"Nakuru",ci:"Nakuru",et:"FULL_TIME",el:"MID",ed:"CERTIFICATE",smin:35000,smax:55000,sd:"SHOW_RANGE",f:false,d:"KenGen is hiring qualified Electricians for our power plants. You will install, maintain, and repair electrical systems and equipment. A valid electrical wireman license and experience in industrial electrical work are required."},
  {t:"Tour Guide",o:"naivas",c:"HOSPITALITY",s:"TOURISM_OPERATIONS",ct:"Nakuru",ci:"Nakuru",et:"PART_TIME",el:"ENTRY",ed:"CERTIFICATE",smin:15000,smax:25000,sd:"NEGOTIABLE",f:false,d:"A tour company in Nakuru is looking for part-time Tour Guides for Lake Nakuru National Park. You will lead game drives, educate visitors about wildlife and conservation, and ensure guest safety. Knowledge of Kenyan wildlife and fluent English and Swahili are required."},
  {t:"Barista",o:"naivas",c:"HOSPITALITY",s:"FOOD_BEVERAGE",ct:"Nairobi",ci:"Nairobi",et:"PART_TIME",el:"ENTRY",ed:"HIGH_SCHOOL",smin:15000,smax:25000,sd:"NEGOTIABLE",f:false,d:"A premium coffee shop in Nairobi is looking for a part-time Barista. You will prepare coffee beverages, maintain equipment, provide excellent customer service, and keep the workspace clean. Previous barista experience is preferred but training will be provided for passionate candidates."},
  {t:"Real Estate Agent",o:"co-op-bank",c:"REAL_ESTATE",s:"REAL_ESTATE_AGENT",ct:"Nairobi",ci:"Nairobi",et:"CONTRACT",el:"ENTRY",ed:"DIPLOMA",smin:null,smax:null,sd:"NEGOTIABLE",f:false,d:"A leading real estate firm in Nairobi is looking for motivated Real Estate Agents. You will list properties, conduct viewings, negotiate deals, and guide clients through the buying and renting process. A certificate in real estate and excellent negotiation skills are required."},
  {t:"Security Supervisor",o:"safaricom",c:"SECURITY_SERVICES",s:"PHYSICAL_SECURITY",ct:"Nairobi",ci:"Nairobi",et:"FULL_TIME",el:"MID",ed:"DIPLOMA",smin:50000,smax:75000,sd:"SHOW_RANGE",f:false,d:"Safaricom is recruiting a Security Supervisor to manage physical security at our headquarters and data centers. You will oversee security guards, conduct security audits, manage access control systems, and respond to security incidents. Previous experience in corporate security management is required."},
];

type OI = { t:string; sl:string; ty:OpportunityType; p:string; ct:string|null; d:string; fu:FundingDisclosure; am:number|null; f:boolean; dl:number; on:boolean; it:boolean; dur:string|null; };

const OPPS: OI[] = [
  {t:"MasterCard Foundation Scholars Program 2026",sl:"mastercard-foundation-scholars-2026",ty:"SCHOLARSHIP",p:"MasterCard Foundation",ct:"Nairobi",d:"The MasterCard Foundation Scholars Program provides full scholarships to economically disadvantaged but academically gifted young Africans to study at top universities. The scholarship covers tuition, accommodation, books, and a stipend.",fu:"FULLY_FUNDED",am:null,f:true,dl:45,on:false,it:false,dur:"4 years"},
  {t:"Google AI Research Internship 2026",sl:"google-ai-research-internship-2026",ty:"TRAINING",p:"Google",ct:null,d:"Google is offering AI Research Internships for African students and early-career researchers. Work alongside Google researchers on cutting-edge machine learning projects. Open to PhD students and postdoctoral researchers.",fu:"SHOW_AMOUNT",am:500000,f:true,dl:30,on:true,it:true,dur:"6 months"},
  {t:"AWARD Fellowship 2026",sl:"award-fellowship-2026",ty:"FELLOWSHIP",p:"AWARD",ct:"Nairobi",d:"The African Women in Agricultural Research and Development (AWARD) Fellowship supports women scientists in agricultural research. The two-year fellowship includes mentoring, career development workshops, and research funding.",fu:"FULLY_FUNDED",am:null,f:false,dl:60,on:false,it:false,dur:"2 years"},
  {t:"USAID Kenya Grants Program",sl:"usaid-kenya-grants-2026",ty:"GRANT",p:"USAID Kenya",ct:"Nairobi",d:"USAID Kenya is offering grants to local NGOs and community-based organizations working in health, education, and economic development. Grants range from KES 5M to KES 50M for projects lasting 1-3 years.",fu:"SHOW_AMOUNT",am:25000000,f:true,dl:45,on:false,it:false,dur:"1-3 years"},
  {t:"Moringa School Software Engineering Bootcamp",sl:"moringa-school-bootcamp-2026",ty:"TRAINING",p:"Moringa School",ct:"Nairobi",d:"Moringa School is offering a 6-month intensive Software Engineering Bootcamp. Learn full-stack web development, data structures, and algorithms. Graduates get job placement support with partner companies.",fu:"PARTIALLY_FUNDED",am:150000,f:false,dl:20,on:false,it:false,dur:"6 months"},
  {t:"Aga Khan Foundation International Scholarship",sl:"aga-khan-scholarship-2026",ty:"SCHOLARSHIP",p:"Aga Khan Foundation",ct:null,d:"The Aga Khan Foundation provides international scholarships for outstanding students from developing countries to pursue postgraduate studies. The scholarship covers tuition and living expenses for master's and PhD programs.",fu:"FULLY_FUNDED",am:null,f:false,dl:90,on:true,it:true,dur:"2-4 years"},
  {t:"Microsoft Learn Africa Mentorship",sl:"microsoft-learn-africa-mentorship",ty:"MENTORSHIP",p:"Microsoft",ct:null,d:"Microsoft Learn Africa offers a 6-month mentorship program connecting African tech professionals with experienced Microsoft engineers. Get career guidance, technical mentorship, and access to Microsoft certification resources.",fu:"NOT_FUNDED",am:null,f:false,dl:25,on:true,it:true,dur:"6 months"},
  {t:"Kenya National Innovation Competition",sl:"kenya-innovation-competition-2026",ty:"COMPETITION",p:"Kenya National Innovation Agency",ct:"Nairobi",d:"The Kenya National Innovation Competition invites innovators and entrepreneurs to present solutions addressing Kenya's development challenges. Winners receive seed funding, incubation support, and mentorship.",fu:"SHOW_AMOUNT",am:5000000,f:true,dl:35,on:false,it:false,dur:null},
  {t:"African Development Bank Internship",sl:"adb-internship-2026",ty:"VOLUNTEER",p:"African Development Bank",ct:"Nairobi",d:"The AfDB offers 3-month internships to young African professionals at its Nairobi regional office. Gain exposure to development finance, policy analysis, and project management in a pan-African institution.",fu:"FULLY_FUNDED",am:null,f:false,dl:30,on:false,it:false,dur:"3 months"},
  {t:"Gates Foundation Global Health Grant",sl:"gates-foundation-health-grant-2026",ty:"GRANT",p:"Bill & Melinda Gates Foundation",ct:null,d:"The Gates Foundation is accepting proposals for innovative global health solutions targeting maternal and child health, infectious diseases, and health systems strengthening in sub-Saharan Africa.",fu:"SHOW_AMOUNT",am:100000000,f:true,dl:60,on:true,it:true,dur:"1-5 years"},
  {t:"Andela Africa Developer Fellowship",sl:"andela-developer-fellowship-2026",ty:"FELLOWSHIP",p:"Andela",ct:"Nairobi",d:"The Andela Developer Fellowship identifies and trains Africa's most talented software developers. Fellows receive world-class technical training, leadership development, and access to a global network of tech companies.",fu:"FULLY_FUNDED",am:null,f:false,dl:20,on:false,it:false,dur:"12 months"},
  {t:"M-KOPA Solar Skills Training",sl:"mkopa-solar-training-2026",ty:"TRAINING",p:"M-KOPA",ct:"Nairobi",d:"M-KOPA is offering free solar installation and maintenance training to youth in Nairobi. The 3-month program includes hands-on training, certification, and job placement support in the growing renewable energy sector.",fu:"FULLY_FUNDED",am:null,f:false,dl:25,on:false,it:false,dur:"3 months"},
  {t:"UN-Habitat Urban Innovation Challenge",sl:"un-habitat-urban-innovation-2026",ty:"COMPETITION",p:"UN-Habitat",ct:"Nairobi",d:"UN-Habitat invites young urban planners, architects, and innovators to propose solutions for sustainable urban development in African cities. Winners receive funding and technical support to implement their ideas.",fu:"SHOW_AMOUNT",am:2000000,f:false,dl:50,on:false,it:false,dur:null},
  {t:"British Council Arts Sponsorship 2026",sl:"british-council-arts-sponsorship-2026",ty:"SPONSORSHIP",p:"British Council Kenya",ct:"Nairobi",d:"The British Council is offering sponsorship to Kenyan artists and creatives for international exhibitions, festivals, and cultural exchanges. Funding covers travel, accommodation, and exhibition costs.",fu:"SHOW_AMOUNT",am:1000000,f:false,dl:45,on:false,it:false,dur:"1-12 months"},
  {t:"TechCrunch Disrupt Nairobi 2026",sl:"techcrunch-disrupt-nairobi-2026",ty:"CONFERENCE",p:"TechCrunch",ct:"Nairobi",d:"TechCrunch Disrupt is coming to Nairobi! Join Africa's top startups, investors, and tech leaders for three days of networking, workshops, and the Startup Battlefield competition. Early bird tickets available now.",fu:"NOT_FUNDED",am:null,f:false,dl:40,on:false,it:false,dur:"3 days"},
];

async function main() {
  console.log('Seeding database...\n');

  // 1. Categories & subcategories
  console.log('1. Seeding 49 categories...');
  for (let i = 0; i < C.length; i++) {
    const [value, label, subs] = C[i];
    const slug = slugify(label);
    const category = await prisma.jobCategory.upsert({
      where: { value },
      update: { label, slug, sortOrder: i, description: `Browse ${label.toLowerCase()} jobs in Kenya. Find verified positions, internships, and career opportunities in the ${label.toLowerCase()} sector.` },
      create: { value, label, slug, sortOrder: i, description: `Browse ${label.toLowerCase()} jobs in Kenya. Find verified positions, internships, and career opportunities in the ${label.toLowerCase()} sector.`, seoTitle: `${label} Jobs in Kenya - JobBoard`, seoDescription: `Explore the latest ${label.toLowerCase()} jobs in Kenya. Apply to verified positions from top employers on JobBoard Kenya.`, icon: value.toLowerCase() },
    });
    for (let j = 0; j < subs.length; j++) {
      const [sv, sl] = subs[j];
      await prisma.jobSubcategory.upsert({
        where: { value: sv },
        update: { label: sl, slug: slugify(sl), sortOrder: j, categoryId: category.id },
        create: { value: sv, label: sl, slug: slugify(sl), sortOrder: j, categoryId: category.id, description: `Find ${sl.toLowerCase()} jobs in Kenya within the ${label.toLowerCase()} category.` },
      });
    }
  }
  console.log('   Done: 49 categories seeded.\n');

  // 2. Organizations
  console.log('2. Seeding 20 organizations...');
  for (const [name, slug, industry, type, hq, verified, desc] of ORGS) {
    await prisma.organization.upsert({
      where: { orgSlug: slug },
      update: { orgName: name, orgIndustry: industry as OrganizationIndustry, orgType: type as OrganizationType, headquarters: hq, isVerified: verified, orgDescription: desc },
      create: { orgName: name, orgSlug: slug, orgIndustry: industry as OrganizationIndustry, orgType: type as OrganizationType, headquarters: hq, isVerified: verified, orgDescription: desc, orgWebsite: `https://${slug.replace(/[^a-z0-9]/g, '')}.co.ke` },
    });
  }
  console.log('   Done: 20 organizations seeded.\n');

  // Build lookup maps
  const allCats = await prisma.jobCategory.findMany();
  const allSubs = await prisma.jobSubcategory.findMany();
  const allOrgs = await prisma.organization.findMany();
  const catMap = new Map(allCats.map(c => [c.value, c]));
  const subMap = new Map(allSubs.map(s => [s.value, s]));
  const orgMap = new Map(allOrgs.map(o => [o.orgSlug, o]));

  // 3. Jobs
  console.log(`3. Seeding ${JOBS.length} jobs...`);
  let jobCount = 0;
  for (const j of JOBS) {
    const cat = catMap.get(j.c);
    const sub = subMap.get(j.s);
    const org = orgMap.get(j.o);
    if (!cat || !sub || !org) { console.log(`   SKIP: ${j.t}`); continue; }
    const jobSlug = slugify(j.t) + '-' + Math.random().toString(36).slice(2, 7);
    const daysAgo = Math.floor(Math.random() * 14);
    const deadline = new Date(Date.now() + (15 + Math.floor(Math.random() * 30)) * 86400000);
    const searchText = [j.t, j.d, org.orgName, j.ci, j.ct].filter(Boolean).join(' ');
    try {
      await prisma.job.create({
        data: { title: j.t, slug: jobSlug, description: j.d, organizationId: org.id, subcategoryId: sub.id, categoryId: cat.id, employmentType: j.et, experienceLevel: j.el, educationLevel: j.ed, locationCity: j.ci, locationCounty: j.ct, salaryMin: j.smin, salaryMax: j.smax, salaryDisclosure: j.sd, salaryCurrency: 'KES', status: 'ACTIVE', featured: j.f, datePosted: new Date(Date.now() - daysAgo * 86400000), deadline, searchText, jobSource: 'MANUAL' },
      });
      jobCount++;
    } catch (e: any) {
      if (e?.code === 'P2002') console.log(`   DUPLICATE slug: ${j.t}`);
      else throw e;
    }
  }
  console.log(`   Done: ${jobCount} jobs seeded.\n`);

  // 4. Opportunities
  console.log(`4. Seeding ${OPPS.length} opportunities...`);
  for (const o of OPPS) {
    await prisma.opportunity.upsert({
      where: { slug: o.sl },
      update: {},
      create: { title: o.t, slug: o.sl, type: o.ty, providerName: o.p, description: o.d, locationCity: o.ct, locationCounty: o.ct, fundingDisclosure: o.fu, fundingAmount: o.am, fundingCurrency: 'KES', status: 'ACTIVE', featured: o.f, datePosted: new Date(Date.now() - Math.floor(Math.random() * 10) * 86400000), deadline: new Date(Date.now() + o.dl * 86400000), isOnline: o.on, openToInternational: o.it, duration: o.dur, howToApply: `Visit the official website of ${o.p} to submit your application before the deadline. Ensure you meet all eligibility criteria and prepare all required documents in advance.` },
    });
  }
  console.log(`   Done: ${OPPS.length} opportunities seeded.\n`);

  console.log('Seed completed successfully!');
}

main().catch((e) => { console.error('Seed error:', e); process.exit(1); }).finally(() => prisma.$disconnect());